version: 2
jobs:
  make-eksctl-image:
    docker:
      - image: weaveworks/eksctl-build:base-latest
    environment:
        GOCACHE: /home/circleci/.cache/go-build/
        GOPATH: /home/circleci/go
    steps:
      - checkout
      - restore_cache:
            keys:
                - go-cache-{{ .Branch }}-{{ .Revision }}
                - go-cache-{{ .Branch }}-
                - go-cache-
      - setup_remote_docker: {docker_layer_caching: true}
      - run: mkdir -p ./test-results/ginkgo
      - run: make eksctl-image
      - run: sudo chown -R circleci.circleci /home/circleci/.cache/go-build/ /home/circleci/go/pkg/mod/
      - save_cache:
            key: go-cache-{{ .Branch }}-{{ .Revision }}
            paths:
                - "/home/circleci/.cache/go-build/"
                - "/home/circleci/go/pkg/mod/"
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
  make-release-candidate:
    docker:
      - image: weaveworks/eksctl-build:base-latest
    environment:
        GOCACHE: /home/circleci/.cache/go-build/
        GOPATH: /home/circleci/go
    steps:
      - checkout
      - restore_cache:
            keys:
                - go-cache-{{ .Branch }}-{{ .Revision }}
                - go-cache-{{ .Branch }}-
                - go-cache-
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
            name: Create release candidate binaries for all plaforms and upload to GitHub
            command: make release-candidate
            no_output_timeout: 21m

  make-release:
    docker:
      - image: weaveworks/eksctl-build:base-latest
    environment:
        GOCACHE: /home/circleci/.cache/go-build/
        GOPATH: /home/circleci/go
    steps:
      - checkout
      - restore_cache:
            keys:
                - go-cache-{{ .Branch }}-{{ .Revision }}
                - go-cache-{{ .Branch }}-
                - go-cache-
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
            name: Create release binaries for all plaforms and upload to GitHub
            command: make release
            no_output_timeout: 21m

workflows:
  version: 2
  any-commit:
    jobs:
      - make-eksctl-image:
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - make-eksctl-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^latest_release$/
      - make-release-candidate:
          requires: [make-eksctl-image]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+/
      - make-release:
          requires: [make-eksctl-image]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
