name: Commit Workflow
on: [push]

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://weaveworks/eksctl-build:b0aa27c30e3f533cdc861a471a0f01f624c7f3d5
        name: Run make lint
        with:
          entrypoint: make
          args: lint
      - uses: docker://weaveworks/eksctl-build:b0aa27c30e3f533cdc861a471a0f01f624c7f3d5
        name: Run make check-all-generated-files-up-to-date
        with:
          entrypoint: make
          args: check-all-generated-files-up-to-date
      - uses: docker://weaveworks/eksctl-build:b0aa27c30e3f533cdc861a471a0f01f624c7f3d5
        name: Run make unit-test
        with:
          entrypoint: make
          args: unit-test
      - uses: docker://weaveworks/eksctl-build:b0aa27c30e3f533cdc861a471a0f01f624c7f3d5
        name: Run make build-integration-test
        with:
          entrypoint: make
          args: build-integration-test
      - uses: docker://weaveworks/eksctl-build:b0aa27c30e3f533cdc861a471a0f01f624c7f3d5
        name: Run make build
        with:
          entrypoint: make
          args: build
